In [ ]:
# Programming for data analysis- assingment#

# Numpy. random package

# Content:

- Explanation of the overall purpose of the numpy.random package.
- 1. Expalnation and analyzis of numpy.random package four contents: simply random data,
- 2. What is and how it works permutations in numpy.random package.
- 3. What does mean the distribution in that package.
- 4. How to generate random numbers with nupy.range package.




- Overview
  Python and Numpy provide us with powerful functionalities to calculate problems from statistics and generate probability theory, and of course to manipulate big data set.
   It provides a high- performance multidimencional array object, tools for working with these arrays.Because NumPy functions operate on numbers, they are especially useful for data science, statistics, and machine learning.
   NumPy has become particularly important for “machine learning” and “deep learning,” since these often involve large datasets of numeric data. When we’re doing machine learning and deep learning, numeric data manipulation is a very big part of the workflow.
   For example, if you want to do some data analysis, we’ll often be working with tables of numbers; so working with data, we need to organize, clean, reshape and transform it. so it is very handy and excellent tool kit.
  NumPy. random package is an open-source   add-on   modules   to   Python   that   provide common mathematical  and  numerical  routines in pre-compiled functions.   
  The  Numpy.random package  provides  basic  routines  for  analyzing large  arrays  and  matrices  of  numeric  data. 
   An  array is  a data structure that stores values of same data type. While python lists can contain values corresponding to different data types. For egzample: numpy.random.rand(a0, a1, …, an) : creates an array of specified shape and fills it with random values.
  
 
  

- 1. What is random numbers, and simply random data?
   
   Random numbers have been used for thousands of years. The meaning of random  is - to leave the end result up to random chance. Random number generators in a computer are similar — they’re an attempt to achieve an unpredictable, random result.
   
   Simply random data in Numpy.random package is return of a sample (or samples) from the “standard normal” distribution. Return random integers from low to high. 

For example:
- First of all we have to import numpy random package. I installed Python 3.7 package through Anakonda site, so numpy random package is included into Python package, so we do not need to install it separately. Numpy random is very common and usefull package for data analysis. I will show some examples why it is so usefull.



In [1]:
#Imported numpy:
import numpy as np
  
a = np.array ([1,2,3])
# a= is variable

print(a)

# So I got output as you see 1, 2, 3 

[1 2 3]


In [3]:
# Wroted to arrays:
import numpy as np
    
a = np.array([(1,2,3),(4,5,6)])  

print(a)

[[1 2 3]
 [4 5 6]]


In [1]:
import numpy as np
a = np.zeros(3)
a


array([0., 0., 0.])

In [2]:
b = np.zeros(9)
b



array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
b.shape # We can find out shape of the array. As at work place we would need to change a lot times the shape of the arrays.


(9,)

In [5]:
b.shape =(9, 1)
b

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [12]:
z = np.ones(10)  # Created different size of the arrays. I made array with populated of ones.
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
z.shape = (10, 1) # We can make changes in the shape. As i wroted shape from 10 to 1.
z

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [14]:
z = np.ones (10)  # i checked float of the array, by typing in program type (z[0])
type(z[0])

numpy.float64

In [9]:
z = np.empty(2)  # Empty will create an empty space in mine array.
z


array([7.56600486e-307, 1.69118787e-306])

In [10]:
z = np.linspace(1, 5, 3) #Created a range whitch starting from 1 to 5 with 3 elements.  It is very handy then I will be creating plots.
z

array([1., 3., 5.])

In [16]:
z = np.array ([10, 30]) # To create a array in numpy, we need to add the list for eg. from 10 to 30 in the brackets.
z

array([10, 30])

In [20]:
b_list = [1,2,3,4,5,6,7,8,9,10]
y = np.array([b_list])
y

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [21]:
type (y)

numpy.ndarray

In [22]:
a_list = [[1,2,3,4,5,6],[6,5,4,3,2,1]] # Created two array lists.
x = np.array([a_list])
x

array([[[1, 2, 3, 4, 5, 6],
        [6, 5, 4, 3, 2, 1]]])

- 2. What is permutations in numpy random package means?
   Randomly permute a sequence, or return a permuted range.
   If x is a multi-dimensional array, it is only shuffled along its first index.


In [54]:
np.random.permutation(5)

array([4, 2, 3, 1, 0])

- 3. What does mean the distribution in that package?
  Simple random data Return a sample (or samples) from the “standard normal” distribution.

In [56]:
R = np. arange (8)
np.random.shuffle (R)
R

array([6, 1, 4, 2, 7, 5, 3, 0])

-  4. How to generate random numbers from Numpy,random package. I will write some egzamples.

    First of all I need to import random in Jupyter notebook. To do that I will type a program below:

In [29]:
import random

In [34]:
random.random() # Wroted random float, which will generate float between 1 and 0. (0.0 <= x < 1.0). Every time then I press on same cell Shift+Enter, gives each next random number

0.799131139100144

In [38]:
random.uniform(2.0, 30.0) # Random float between whose two parameters- from 2.0 <= x <30.0. With pressing every time shift +Enter, will give random numbers.

15.800167771758984

In [42]:
random.randint (0, 100) # Will generate random numbers between the range 0-100

73

- Very useful method for the companys is random. choice. I will try to show egzamples:


In [46]:
random.choice (["H","C"]) # This method gives just to option Herb or Coin side, because probability that coin will turn or Herb side or Coin side is 50 to 50.So everytime than I escape from this cell, will give me Or Herb or Coin output, because is just two choices.

'C'

In [50]:
coin = ["H", "C"]      # This command gives output of random choices in a row.
result = [random.choice(coin) for r in range(10)]
print(result)

['C', 'H', 'H', 'C', 'H', 'H', 'C', 'C', 'C', 'H']


In [51]:
result.count ("H") # It  find out how many times Herbs turns

5

In [23]:
np.random.seed(0)             
d = np.random.randint(8, size=5) # Created random arrays using randomint method in numpy.random.
d



array([4, 7, 5, 0, 3])

In [24]:
d[0]    # It shows the first element of the array, whitch in my case it is 4.

4

In [26]:
d[0:4]  # If I wrote the range from 0 to 4 it gives that output:

array([4, 7, 5, 0])

In [28]:
d[-1]

3

 Egzample 2:
 

In [11]:
import random

for i in range (10):
     print (random.normalvariate(0, 1))

0.5683910741298476
-0.7769321469498018
-0.6361989092083598
-0.04550556169378423
-1.345385635587545
0.241103370931791
1.0028666624715252
-0.6175014835275009
0.06901381067572918
0.32572423328397065
